using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using BepInEx;

namespace SskCnPoc
{
    /// <summary>
    /// Exporter that writes extracted translation entries to a gettext-style PO-ish file
    /// for translators. This is a simplified Ren'Py/gettext-like extractor that writes
    /// "msgid" (original) and empty "msgstr" entries. It includes context (if available)
    /// and groups entries to make it easier to import into translation platforms.
    ///
    /// Usage: call Exporter.ExportToPo(outputPath) after TranslationManager has loaded.
    /// </summary>
    internal static class Exporter
    {
        /// <summary>
        /// Export all collected translation keys to a .po-like file.
        /// It uses TranslationManager.Map (exact matches) and also dumps
        /// template and multi-template entries into a separate sections.
        /// </summary>
        public static void ExportToPo(string outputPath)
        {
            try
            {
                var sb = new StringBuilder();

                sb.AppendLine("# Sunless Skies translation export");
                sb.AppendLine("# Generated by SskCnPoc Exporter");
                sb.AppendLine($"# Date: {DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ}");
                sb.AppendLine();

                // 1) Exact map entries
                sb.AppendLine("# --- Exact entries ---");
                foreach (var kv in TranslationManager.Map.OrderBy(k => k.Key))
                {
                    AppendPoEntry(sb, kv.Key, kv.Value, "exact");
                }

                // 2) Template entries (single placeholder)
                sb.AppendLine();
                sb.AppendLine("# --- Template entries ---");
                foreach (var list in TranslationManager.TemplatesByFirstChar.Values)
                {
                    foreach (var tpl in list)
                    {
                        var orig = tpl.Prefix + "{0}" + tpl.Suffix;
                        AppendPoEntry(sb, orig, tpl.ZhTemplate, "template");
                    }
                }
                foreach (var tpl in TranslationManager.TemplatesWithEmptyPrefix)
                {
                    var orig = tpl.Prefix + "{0}" + tpl.Suffix;
                    AppendPoEntry(sb, orig, tpl.ZhTemplate, "template");
                }

                // 3) Multi-template entries
                sb.AppendLine();
                sb.AppendLine("# --- Multi-template entries ---");
                foreach (var list in TranslationManager.MultiTemplatesByFirstChar.Values)
                {
                    foreach (var mt in list)
                    {
                        // reconstruct a readable original pattern from parts
                        string orig = string.Join("{n}", mt.Parts);
                        AppendPoEntry(sb, orig, mt.ZhTemplate, "multi-template");
                    }
                }
                foreach (var mt in TranslationManager.MultiTemplatesWithEmptyPrefix)
                {
                    string orig = string.Join("{n}", mt.Parts);
                    AppendPoEntry(sb, orig, mt.ZhTemplate, "multi-template");
                }

                // 4) Prefix-indexed long entries (optional)
                sb.AppendLine();
                sb.AppendLine("# --- Long entries (prefix-index) ---");
                foreach (var kv in TranslationManager.GetPrefixIndexEntries())
                {
                    AppendPoEntry(sb, kv.orig, kv.trans, "long");
                }

                File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
                Plugin.LogSrc.LogInfo($"Exporter: Wrote translations export to {outputPath}");
            }
            catch (Exception ex)
            {
                Plugin.LogSrc.LogWarning($"Exporter: Failed to export translations: {ex.Message}");
            }
        }

        private static void AppendPoEntry(StringBuilder sb, string orig, string? zh, string context)
        {
            if (string.IsNullOrEmpty(orig)) return;
            // escape quotes
            string esc = orig.Replace("\\", "\\\\").Replace("\"", "\\\"");
            sb.AppendLine($"#. context: {context}");
            sb.AppendLine($"msgid \"{esc}\"");
            sb.AppendLine("msgstr \"\"");
            sb.AppendLine();
        }
    }
}
